### ISSUE TITLE
Images in markdowns not visible

### ISSUE THREAD

**Issue by Rohit-Satyam** [widdowquinn/Teaching-Comp-Genomics-Vis#2]
Hi 

I can see that images are not visible in your markdowns. Rather they are visible as

![JSpecies analysis result window](images/jspecies10.png?raw=True =400x)

**Comment by widdowquinn** [comment]
Hi @Rohit-Satyam - I'm not sure what the issue is, here. GitHub's Markdown syntax is not the same as other Markdown syntax, and these (eight year-old plus!) materials were not written for presentation on GitHub.

You might want to take a look at the `*_UoD.md` files instead, which IIRC use GitHub Markdown syntax.
